#!/usr/bin/env bash

set -e

apt-get -y install sharutils
apt-get -y install vim
apt-get -y install lynx
apt-get -y install curl
apt-get -y install wget
apt-get -y install ncftp
apt-get -y install tmux
apt-get -y install build-essential
apt-get -y install git
apt-get -y install tig
apt-get -y install kdiff3
apt-get -y install subversion
apt-get -y install autoconf
apt-get -y install autoconf-archive
apt-get -y install automake
apt-get -y install autotools-dev
apt-get -y install devscripts
apt-get -y install debhelper
apt-get -y install debmake
apt-get -y install pkg-config
apt-get -y install gcc
apt-get -y install g++
apt-get -y install gdb
apt-get -y install cmake
apt-get -y install bison
apt-get -y install flex
apt-get -y install xsel
apt-get -y install graphviz
apt-get -y install boxes
apt-get -y install asciio
apt-get -y install fontconfig
apt-get -y install fontconfig-config
apt-get -y install ncurses-bin
apt-get -y install libncurses-dev
apt-get -y install ncurses-doc
apt-get -y install libsixel-dev
apt-get -y install libsixel-examples
apt-get -y install libffi-dev
apt-get -y install libxml2-dev
apt-get -y install libxml2-doc
apt-get -y install libxml2-utils
apt-get -y install libcurl4-gnutls-dev
apt-get -y install libgnutls28-dev
apt-get -y install libjwt-gnutls-dev
apt-get -y install expat
apt-get -y install python-setuptools
apt-get -y install python-pip-whl
apt-get -y install python3-setuptools
apt-get -y install python3-pip
apt-get -y install python3-blockdiag
apt-get -y install python3-libxml2
apt-get -y install python3-lxml
apt-get -y install python3-pycurl
apt-get -y install cppman
apt-get -y install perl
apt-get -y install libxml-libxml-perl
apt-get -y install libjson-xs-perl
apt-get -y install libtext-csv-perl
apt-get -y install libtext-csv-xs-perl
apt-get -y install libperl6-form-perl
apt-get -y install visidata
apt-get -y install asciidoctor
apt-get -y install asciidoctor-doc
apt-get -y install ruby-asciidoctor-pdf
apt-get -y install ruby-rouge
apt-get -y install libgdk-pixbuf2.0-dev
apt-get -y install libcairo2-dev
apt-get -y install libpango1.0-dev
apt-get -y install fonts-lyx
apt-get -y install ruby-dev
apt-get -y install nodejs
apt-get -y install qtcreator
apt-get -y install libwinpr2-dev
apt-get -y install gnuplot
apt-get -y install gnuplot-data
apt-get -y install gnuplot-doc
apt-get -y install dconf-editor

#add-apt-repository ppa:freecad-maintainers/freecad-daily
#apt-get update
#apt-get -y install freecad-daily

apt-get -y install freecad kicad
apt-get -y install freecad-python3
apt-get -y install kicad-packages3d
apt-get -y install slic3r
apt-get -y install python3-pyqt5
apt-get -y install python3-vtk7
apt-get -y install freecad-common freecad-python3
apt-get -y install fonts-osifont
apt-get -y install libnglib-dev
apt-get -y install python3-git
apt-get -y install calculix-cgx
apt-get -y install libnglib-dev
apt-get -y install netgen
apt-get -y install python3-netgen
apt-get -y install calculix-ccx
apt-get -y install gmsh
apt-get -y install python3-gmsh
apt-get -y install python3-vtkplotter
apt-get -y install python3-meshio
apt-get -y install meshio-tools
