#!/usr/bin/env bash

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  cat <<EOF
Usage: $0 [-h|--help]
       $0 [--no-dry-run] [--prefix PREFIX]
EOF
  exit 0
fi

DRYRUN=yes
PREFIX=''

if [ "$1" = '--no-dry-run' ]; then
  DRYRUN=no
  shift
fi

if [ "$1" = '--prefix' ]; then
  shift
  if [ -n "$1" ]; then
    PREFIX="$1"
  fi
fi

if [ -z "${PREFIX}" ]; then
  if [ 'no' = "${DRYRUN}" ]; then
    PREFIX="${PREFIX:-${HOME}}"
  else
    PREFIX="$(mktemp -d)"
  fi
fi


if [ 'no' != "${DRYRUN}" ]; then
  echo "Dry-Run mode, install to: '${PREFIX}'"
else
  echo "Install to: '${PREFIX}'"
fi
mkdir -p "${PREFIX}"


case "$(uname -o)" in
  Msys)
	  INSTALL_X="install"
	  INSTALL_R="install"
	  INSTALL_P="install"
	  ;;
  *)
	  INSTALL_X="install -m 0755"
	  INSTALL_R="install -m 0644"
	  INSTALL_P="install -m 0700"
	  ;;
esac

# =============================================================================
# Exit on any errors
set -e
function echoerr() { echo "$@" 1>&2; }
# =============================================================================

# =============================================================================
# Configure some shell variables
PATH="${PATH}:${PREFIX}/.local/bin"
LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${PREFIX}/.local/lib"
DATAROOTDIR="${PREFIX}/.local/share"
# =============================================================================

# =============================================================================
# Autodetect current install capabilities
function has_prog() {
    hash "$1" > /dev/null 2>&1
    return $?
}

REQUIRED_PROGS=(curl git grep install mktemp sed tar)
has_errors=
for p in ${REQUIRED_PROGS[@]};
do
    if ! has_prog "${p}"; then
       echoerr " - ${p} required"
       has_errors=Yes
    fi
done
if ! has_prog uudecode && ! has_prog perl; then
    echoerr " - uudecode or perl required"
    has_errors=Yes
fi
[[ -z "${has_errors}" ]] || exit 1

os_name=
if has_prog uname; then
    os_name=$(uname -s)
fi
# =============================================================================

# =============================================================================
# Prepare temporary directory to unarchive files
# ----------------------------------------------
RUN_CWD=$(pwd)
SHAR_TMPDIR=$(mktemp -d)
cd "${SHAR_TMPDIR}"
echo "Unsharing files in '${SHAR_TMPDIR}' ..."
cat <<'SETUP_SHAR_EOF'> setup.shar
# @SHAR_ARCHIVE@
SETUP_SHAR_EOF
/bin/sh setup.shar > /dev/null
# =============================================================================

# Make uudecode available if not present on system
if ! has_prog uudecode; then
    mv scripts/uudecode.pl uudecode
    chmod 0755 uudecode
    export PATH="${PWD}:${PATH}"
fi

# Prepare backups directory
DATE=$(date '+%Y%m%d')
HOUR=$(date '+%H%M%S')
BACKUPDIR="${PREFIX}/.backups/${DATE}/${HOUR}"
${INSTALL_P} -d "${BACKUPDIR}"

# Backup files
echo "shell ..."
if [ -e "${PREFIX}/.profile" ]; then
    cp -f "${PREFIX}/.profile" "${BACKUPDIR}"
fi
if [ -e "${PREFIX}/.bash_profile" ]; then
    cp -f "${PREFIX}/.bash_profile" "${BACKUPDIR}"
fi
if [ -e "${PREFIX}/.bashrc" ]; then
    cp -f "${PREFIX}/.bashrc" "${BACKUPDIR}"
fi
if [ ! -e "${PREFIX}/.path_dirs" ]; then
    cat <<DOT_PROFILE_PATHS_EOF > "${PREFIX}/.path_dirs"
# Directory path in this file are scanned by .bash_profile
# to setup the following variables:
#  - PATH
#  - LD_LIBRARY_PATH
#  - MANPATH
#  - INFOPATH
#  - PERL5LIB
#  - PKG_CONFIG_PATH

${PREFIX}/.local
${PREFIX}/.local/share/perl5
DOT_PROFILE_PATHS_EOF
fi
${INSTALL_R} dot/profile      "${PREFIX}/.profile"
${INSTALL_R} dot/bash_profile "${PREFIX}/.bash_profile"
${INSTALL_R} dot/bashrc       "${PREFIX}/.bashrc"

# .local setup
echo "local ..."
${INSTALL_X} -d "${PREFIX}/.local/bin"
${INSTALL_X} -d "${PREFIX}/.local/lib"
${INSTALL_X} -d "${PREFIX}/.local/opt"
${INSTALL_X} -d "${PREFIX}/.local/share"
${INSTALL_X} -d "${PREFIX}/.local/share/man/man1"
${INSTALL_X} -d "${PREFIX}/.local/var"
${INSTALL_X} -d "${PREFIX}/.local/var/lock"
${INSTALL_X} -d "${PREFIX}/.local/var/log"
${INSTALL_X} -d "${PREFIX}/.local/var/run"
${INSTALL_X} -d "${PREFIX}/.local/etc/cron"
${INSTALL_X} -d "${PREFIX}/.local/etc/profile.d"
${INSTALL_X} scripts/runcron "${PREFIX}/.local/bin"
PATH="${PATH}:${PREFIX}/.local/bin"
export PATH

# Cron setup
echo "cron ..."
if has_prog crontab; then
    ${INSTALL_X} -d "${PREFIX}/.local/etc/cron"
    ${INSTALL_X} -d "${PREFIX}/.local/etc/cron/hourly"
    ${INSTALL_X} -d "${PREFIX}/.local/etc/cron/daily"
    ${INSTALL_X} -d "${PREFIX}/.local/etc/cron/daily-4"
    ${INSTALL_X} -d "${PREFIX}/.local/etc/cron/daily-8"
    ${INSTALL_X} -d "${PREFIX}/.local/etc/cron/daily-12"
    ${INSTALL_X} -d "${PREFIX}/.local/etc/cron/daily-16"
    ${INSTALL_X} -d "${PREFIX}/.local/etc/cron/daily-20"
    ${INSTALL_X} -d "${PREFIX}/.local/etc/cron/weekly"
    ${INSTALL_X} -d "${PREFIX}/.local/etc/cron/monthly"
    ${INSTALL_X} -d "${PREFIX}/.local/etc/cron/yearly"
    ${INSTALL_X} -d "${PREFIX}/.local/etc/cron/commands"
    touch "${PREFIX}/.local/etc/cron/environ.bash"

    crontab -l > "${BACKUPDIR}/crontab"
    tmpcrontab=$(mktemp)
    grep -v "${PREFIX}/.local/bin/runcron" "${BACKUPDIR}/crontab" \
         > "${tmpcrontab}"
    echo "0  * * * *" "${PREFIX}/.local/bin/runcron hourly"   >> "${tmpcrontab}"
    echo "0  0 * * *" "${PREFIX}/.local/bin/runcron daily"    >> "${tmpcrontab}"
    echo "0  4 * * *" "${PREFIX}/.local/bin/runcron daily-4"  >> "${tmpcrontab}"
    echo "0  8 * * *" "${PREFIX}/.local/bin/runcron daily-8"  >> "${tmpcrontab}"
    echo "0 12 * * *" "${PREFIX}/.local/bin/runcron daily-12" >> "${tmpcrontab}"
    echo "0 16 * * *" "${PREFIX}/.local/bin/runcron daily-16" >> "${tmpcrontab}"
    echo "0 20 * * *" "${PREFIX}/.local/bin/runcron daily-20" >> "${tmpcrontab}"
    echo "0  0 * * 0" "${PREFIX}/.local/bin/runcron weekly"   >> "${tmpcrontab}"
    echo "0  0 1 * *" "${PREFIX}/.local/bin/runcron monthly"  >> "${tmpcrontab}"
    echo "0  0 1 1 *" "${PREFIX}/.local/bin/runcron yearly"   >> "${tmpcrontab}"
    crontab "${tmpcrontab}"
    rm -f "${tmpcrontab}"
fi

# Cygwin
case "${os_name}" in
    CYGWIN*)
        echo "Cygwin ..."
        if [ -e "${PREFIX}/.XWinrc" ]; then
            cp -f "${PREFIX}/.XWinrc" "${BACKUPDIR}"
        fi
        ${INSTALL_R} dot/XWinrc         "${PREFIX}/.XWinrc"
        ${INSTALL_X} scripts/hyper-v    "${PREFIX}/.local/bin"
        ${INSTALL_R} man/hyper-v.1      "${PREFIX}/.local/share/man/man1"
        ${INSTALL_X} scripts/apt-cyg    "${PREFIX}/.local/bin"
        ${INSTALL_X} scripts/msvc-shell "${PREFIX}/.local/bin"
        ${INSTALL_R} man/msvc-shell.1   "${PREFIX}/.local/share/man/man1"
        ${INSTALL_X} scripts/bshell.bat "${PREFIX}/.local/bin"
        ;;
    MINGW*)
        ${INSTALL_X} scripts/msvc-shell "${PREFIX}/.local/bin"
        ${INSTALL_R} man/msvc-shell.1   "${PREFIX}/.local/share/man/man1"
        ${INSTALL_X} scripts/bshell.bat "${PREFIX}/.local/bin"
        ;;
esac

# Python
echo "Python ..."
echo " - checking if cppman is installed"
if ! has_prog cppman; then
    if has_prog pip3; then
        echo " - installing cppman plugin with pip3"
        [ 'yes' != "${DRYRUN}" ] && pip3 install --user cppman > install.log 2>&1
    fi
fi

# Ruby
if [ -e "${PREFIX}/.gemrc" ]; then
    cp -f "${PREFIX}/.gemrc" "${BACKUPDIR}"
fi
${INSTALL_R} dot/gemrc "${PREFIX}/.gemrc"

# vim
echo "vim ..."
if [ -e "${PREFIX}/.vimrc" ]; then
    cp -f "${PREFIX}/.vimrc" "${BACKUPDIR}"
fi
${INSTALL_R} dot/vimrc "${PREFIX}/.vimrc"

# tmux
echo "tmux ..."
if [ -e "${PREFIX}/.tmux.conf" ]; then
    cp -f "${PREFIX}/.tmux.conf" "${BACKUPDIR}"
fi
${INSTALL_R} dot/tmux.conf "${PREFIX}/.tmux.conf"
${INSTALL_X} scripts/yank  "${PREFIX}/.local/bin"
${INSTALL_R} man/yank.1    "${PREFIX}/.local/share/man/man1"

echo "terminfo ..."
if has_prog tic; then
    has_tmux256_terminfo=""
    if [ -e /lib/terminfo/t/tmux-256color ]; then
        has_tmux256_terminfo="y"
    fi
    if [ -e /usr/share/terminfo/t/tmux-256color ]; then
        has_tmux256_terminfo="y"
    fi
    if [ -e "${PREFIX}/.terminfo/t/tmux-256color" ]; then
        has_tmux256_terminfo="y"
    fi
    if [ -z "${has_tmux256_terminfo}" ]; then
        mkdir -p "${PREFIX}/.terminfo"
        tic -o "${PREFIX}/.terminfo" data/tmux-256color.tinfo
    fi
fi

# Perl
echo "Perl ..."
if [ ! -e "${PREFIX}/.local/share/perl5" ]; then
    perl_local_lib=local-lib-2.000029
    curl -s -O "http://www.cpan.org/authors/id/H/HA/HAARG/${perl_local_lib}.tar.gz"
    tar zxf "${perl_local_lib}.tar.gz"
    cd  "${perl_local_lib}"
    perl Makefile.PL "--bootstrap=${PREFIX}/.local/share/perl5" > install.log 2>&1
    make test > install.log 2>&1 && make install > install.log 2>&1
    cd ..
    perl "-I${PREFIX}/.local/share/perl5/lib/perl5" "-Mlocal::lib=${PREFIX}/.local/share/perl5" \
        > "${PREFIX}/.local/etc/profile.d/perl5.sh"
    source "${PREFIX}/.local/etc/profile.d/perl5.sh"
fi

# Scripts
${INSTALL_X} scripts/codefmt       "${PREFIX}/.local/bin"
${INSTALL_R} man/codefmt.1         "${PREFIX}/.local/share/man/man1"
${INSTALL_X} scripts/codemv        "${PREFIX}/.local/bin"
${INSTALL_R} man/codemv.1          "${PREFIX}/.local/share/man/man1"
${INSTALL_X} scripts/plgen         "${PREFIX}/.local/bin"
${INSTALL_R} man/plgen.1           "${PREFIX}/.local/share/man/man1"
${INSTALL_X} scripts/sixel2tmux    "${PREFIX}/.local/bin"
${INSTALL_R} man/sixel2tmux.1      "${PREFIX}/.local/share/man/man1"
${INSTALL_X} scripts/byzanz-helper "${PREFIX}/.local/bin"
${INSTALL_R} man/byzanz-helper.1   "${PREFIX}/.local/share/man/man1"
${INSTALL_X} scripts/ffmpeg-helper "${PREFIX}/.local/bin"
${INSTALL_R} man/ffmpeg-helper.1   "${PREFIX}/.local/share/man/man1"

# Autoconf cache
echo "Autoconf cache ..."
if [ ! -e "${PREFIX}/.local/etc/config.site" ]; then
    cp data/config.site "${PREFIX}/.local/etc/config.site"
fi

# Gnulib
echo "Gnulib ..."
if ! has_prog gnulib-tool; then
    if [ ! -e "${PREFIX}/.local/share/gnulib" ]; then
        git clone git://git.savannah.gnu.org/gnulib.git "${PREFIX}/.local/share/gnulib" > install.log 2>&1
    fi
    ln -s "${PREFIX}/.local/share/gnulib/gnulib-tool"    "${PREFIX}/.local/bin/gnulib-tool"
    ln -s "${PREFIX}/.local/share/gnulib/gnulib-tool.py" "${PREFIX}/.local/bin/gnulib-tool.py"
fi

# TeX
echo "TeX ..."
if has_prog kpsewhich; then
    texmf_home=$(kpsewhich -var-value TEXMFHOME)
    if [ ! -e "${texmf_home}/tex/latex/createspace" ]; then
        mkdir -p "${texmf_home}/tex/latex/"
        git clone https://github.com/aginiewicz/createspace.git "${texmf_home}/tex/latex/createspace" > install.log 2>&1
    fi
fi

# # Asciidoctor
# echo "Asciidoctor ..."
# if has_prog gem && has_prog bison && has_prog flex && has_prog cmake; then
#     gem install --user-install pygments.rb
#     gem install --user-install asciimath
#     gem install --user-install asciidoctor-pdf
#     gem install --user-install mathematical
#     gem install --user-install asciidoctor-mathematical
#     gem install --user-install asciidoctor-diagram
# fi


echo "Finished installing in '${PREFIX}'. Backup created in '${BACKUPDIR}'."
