# .bash_profile executed by bash(1) for login shells.

# Save system path the first time
if [ -z "${SYSTEM_PATH}" ] ; then
  export SYSTEM_PATH="${PATH}"
  export SYSTEM_PERL5LIB="${PERL5LIB}"
fi

# source the users bashrc if it exists
if [ -f "${HOME}/.bashrc" ] ; then
  source "${HOME}/.bashrc"
fi

XTRAPATHS="/opt /opt/local ${HOME}/opt ${HOME}/local"
for xtrad in ${XTRAPATHS};
do
  # Set PATH so it includes user's private bin if it exists
  if [ -d "${xtrad}/bin" ]; then
    PATH="${xtrad}/bin:${PATH}"
  fi
 
  # Set PATH so it includes user's private lib if it exists
  if [ -d "${xtrad}/lib" ]; then
    PATH="${xtrad}/lib:${PATH}"
  fi
 
  # Set PKG_CONFIG_PATH so it includes user's private if it exists
  if [ -d "${xtrad}/lib/pkgconfig" ]; then
    PKG_CONFIG_PATH="${xtrad}/lib/pkgconfig:${PKG_CONFIG_PATH}"
  fi
 
  # Set MANPATH so it includes users' private man if it exists
  if [ -d "${xtrad}/man" ]; then
    MANPATH="${xtrad}/man:${MANPATH}"
  fi
  if [ -d "${xtrad}/share/man" ]; then
    MANPATH="${xtrad}/share/man:${MANPATH}"
  fi
 
  # Set INFOPATH so it includes users' private info if it exists
  if [ -d "${xtrad}/info" ]; then
    INFOPATH="${xtrad}/info:${INFOPATH}"
  fi

  # Set PERL5LIB so it includes user's private perl if it exists
  if [ -d "${xtrad}/lib/perl5" ]; then
    PERL5LIB="${xtrad}:${PERL5LIB}"
  fi
done
export PATH

# Prompt customization
SETXTERMTITLE='\[\e]0;\h - \w\a\]\n'
PS1='\[\e[32m\](chroot) \u@\h \[\e[35m\]\t \[\e[33m\]\w\[\e[0m\]\n\$ '
if [[ "$TERM" == *"xterm"* ]]; then
    PS1="${SETXTERMTITLE}${PS1}"
fi
export PS1

# For nedit bug...
export XLIB_SKIP_ARGB_VISUALS=1

# Remote PulseAudio
export PULSE_SERVER=tcp:localhost:4713
export SDL_AUDIODRIVER=pulse

alias xterm='xterm -rv -sb -rightbar +fbx'

