#!/usr/bin/env bash

apt-cyg install cron
apt-cyg install cygrunsrv
apt-cyg install libattr1
apt-cyg install syslog-ng
apt-cyg install arc
apt-cyg install bzip2
apt-cyg install libarchive13
apt-cyg install libbz2_1
apt-cyg install libbz2-devel
apt-cyg install libhdf5_10
apt-cyg install libzzip0.13
apt-cyg install sharutils
apt-cyg install unace
apt-cyg install unalz
apt-cyg install unzip
apt-cyg install xz
apt-cyg install zip
apt-cyg install aalib-devel
apt-cyg install astyle
apt-cyg install autoconf
apt-cyg install autoconf-archive
apt-cyg install automake
apt-cyg install binutils
apt-cyg install bison
apt-cyg install byacc
apt-cyg install bzr
apt-cyg install cgdb
apt-cyg install clang
apt-cyg install clisp
apt-cyg install cmake
apt-cyg install cmake-doc
apt-cyg install colorgcc
apt-cyg install cygwin-devel
apt-cyg install dmalloc
apt-cyg install eventlog
apt-cyg install gcc-ada
apt-cyg install gcc-cilkplus
apt-cyg install gcc-core
apt-cyg install gcc-fortran
apt-cyg install gcc-g++
apt-cyg install gdb
apt-cyg install gendef
apt-cyg install gettext-devel
apt-cyg install git
apt-cyg install git-clang-format
apt-cyg install git-email
apt-cyg install git-gui
apt-cyg install gitk
apt-cyg install git-review
apt-cyg install help2man
apt-cyg install htmldoc
apt-cyg install indent
apt-cyg install kbproto
apt-cyg install libargp
apt-cyg install libgcab1.0_0
apt-cyg install libgnutls-devel
apt-cyg install libltdl7
apt-cyg install libmcrypt-devel
apt-cyg install libmsi0
apt-cyg install libreadline-devel
apt-cyg install libtasn1-devel
apt-cyg install make
apt-cyg install mcpp
apt-cyg install mercurial
apt-cyg install msitools
apt-cyg install nasm
apt-cyg install patch
apt-cyg install patchutils
apt-cyg install perl-ExtUtils-XSpp
apt-cyg install pkg-config
apt-cyg install po4a
apt-cyg install poedit
apt-cyg install pylint
apt-cyg install swig
apt-cyg install texinfo
apt-cyg install texinfo-tex
apt-cyg install umbrello
apt-cyg install w32api-headers
apt-cyg install w32api-runtime
apt-cyg install windows-default-manifest
apt-cyg install wixl
apt-cyg install xextproto
apt-cyg install xmltoman
apt-cyg install xproto
apt-cyg install xsd
apt-cyg install yasm
apt-cyg install asciidoc
apt-cyg install libgeoclue0
apt-cyg install libzmq-doc
apt-cyg install man-pages-posix
apt-cyg install ed
apt-cyg install preview-latex
apt-cyg install scintilla-win32
apt-cyg install vim
apt-cyg install vim-clang-format
apt-cyg install vim-common
apt-cyg install vim-doc
apt-cyg install xxd
apt-cyg install checkbashisms
apt-cyg install colorgcc
apt-cyg install perl
apt-cyg install perl_autorebase
apt-cyg install perl_base
apt-cyg install perl_manpages
apt-cyg install perl_pods
apt-cyg install perl-Algorithm-Diff
apt-cyg install perl-Archive-Zip
apt-cyg install perl-Authen-SASL
apt-cyg install perl-Authen-SASL-XS
apt-cyg install perl-autovivification
apt-cyg install perl-B-Hooks-EndOfScope
apt-cyg install perl-Business-ISBN
apt-cyg install perl-Business-ISBN-Data
apt-cyg install perl-Business-ISMN
apt-cyg install perl-Business-ISSN
apt-cyg install perl-Cairo
apt-cyg install perl-Capture-Tiny
apt-cyg install perl-Carp
apt-cyg install perl-Class-Accessor
apt-cyg install perl-Class-Data-Inheritable
apt-cyg install perl-Class-Singleton
apt-cyg install perl-Class-XSAccessor
apt-cyg install perl-common-sense
apt-cyg install perl-Config-AutoConf
apt-cyg install perl-Config-Perl-V
apt-cyg install perl-Config-Tiny
apt-cyg install perl-CPAN-Changes
apt-cyg install perl-CPAN-DistnameInfo
apt-cyg install perl-CPAN-Meta
apt-cyg install perl-CPAN-Meta-Check
apt-cyg install perl-CPAN-Meta-Requirements
apt-cyg install perl-CPAN-Meta-YAML
apt-cyg install perl-CPAN-Reporter
apt-cyg install perl-CPAN-Testers-Report
apt-cyg install perl-Crypt-OpenSSL-Bignum
apt-cyg install perl-Data-Compare
apt-cyg install perl-Data-Dump
apt-cyg install perl-Data-GUID
apt-cyg install perl-Data-OptList
apt-cyg install perl-Data-Uniqid
apt-cyg install perl-Data-UUID
apt-cyg install perl-Date-Manip
apt-cyg install perl-Date-Simple
apt-cyg install perl-DateTime
apt-cyg install perl-DateTime-Locale
apt-cyg install perl-DateTime-TimeZone
apt-cyg install perl-DBI
apt-cyg install perl-Devel-Autoflush
apt-cyg install perl-Devel-StackTrace
apt-cyg install perl-Devel-Symdump
apt-cyg install perl-Digest-HMAC
apt-cyg install perl-Digest-SHA
apt-cyg install perl-Digest-SHA1
apt-cyg install perl-Dist-CheckConflicts
apt-cyg install perl-Encode-Locale
apt-cyg install perl-Error
apt-cyg install perl-Eval-Closure
apt-cyg install perl-Exception-Class
apt-cyg install perl-Exporter-Tiny
apt-cyg install perl-ExtUtils-CBuilder
apt-cyg install perl-ExtUtils-Depends
apt-cyg install perl-ExtUtils-Helpers
apt-cyg install perl-ExtUtils-LibBuilder
apt-cyg install perl-ExtUtils-MakeMaker
apt-cyg install perl-ExtUtils-PkgConfig
apt-cyg install perl-ExtUtils-XSpp
apt-cyg install perl-File-Copy-Recursive
apt-cyg install perl-File-Find-Object
apt-cyg install perl-File-Find-Object-Rule
apt-cyg install perl-File-Find-Rule
apt-cyg install perl-File-HomeDir
apt-cyg install perl-File-Listing
apt-cyg install perl-File-pushd
apt-cyg install perl-File-Remove
apt-cyg install perl-File-Slurp
apt-cyg install perl-File-Slurper
apt-cyg install perl-File-Slurp-Tiny
apt-cyg install perl-File-Which
apt-cyg install perl-Font-AFM
apt-cyg install perl-Font-TTF
apt-cyg install perl-GD
apt-cyg install perl-Getopt-ArgvFile
apt-cyg install perl-gettext
apt-cyg install perl-HTML-Parser
apt-cyg install perl-HTML-Tagset
apt-cyg install perl-HTTP-Cookies
apt-cyg install perl-HTTP-Daemon
apt-cyg install perl-HTTP-Date
apt-cyg install perl-HTTP-Message
apt-cyg install perl-HTTP-Negotiate
apt-cyg install perl-HTTP-Tiny
apt-cyg install perl-Importer
apt-cyg install perl-inc-latest
apt-cyg install perl-Inline
apt-cyg install perl-Inline-Files
apt-cyg install perl-IO-CaptureOutput
apt-cyg install perl-IO-HTML
apt-cyg install perl-IO-Prompt-Tiny
apt-cyg install perl-IO-Socket-INET6
apt-cyg install perl-IO-Socket-IP
apt-cyg install perl-IO-Socket-SSL
apt-cyg install perl-IO-String
apt-cyg install perl-IO-stringy
apt-cyg install perl-IO-Tty
apt-cyg install perl-IPC-Cmd
apt-cyg install perl-IPC-Run
apt-cyg install perl-IPC-Run3
apt-cyg install perl-JSON
apt-cyg install perl-JSON-MaybeXS
apt-cyg install perl-JSON-PP
apt-cyg install perl-JSON-XS
apt-cyg install perl-Lchown
apt-cyg install perl-libwww-perl
apt-cyg install perl-libxml-perl
apt-cyg install perl-Lingua-Translit
apt-cyg install perl-List-AllUtils
apt-cyg install perl-List-MoreUtils
apt-cyg install perl-List-SomeUtils
apt-cyg install perl-List-UtilsBy
apt-cyg install perl-Log-Log4perl
apt-cyg install perl-LWP-MediaTypes
apt-cyg install perl-LWP-Online
apt-cyg install perl-LWP-Protocol-https
apt-cyg install perl-MailTools
apt-cyg install perl-Metabase-Client-Simple
apt-cyg install perl-Metabase-Fact
apt-cyg install perl-MIME-Base32
apt-cyg install perl-MIME-Charset
apt-cyg install perl-MIME-tools
apt-cyg install perl-MIME-Types
apt-cyg install perl-Module-Build
apt-cyg install perl-Module-Implementation
apt-cyg install perl-Module-Load-Conditional
apt-cyg install perl-Module-Metadata
apt-cyg install perl-Module-Pluggable
apt-cyg install perl-Module-Runtime
apt-cyg install perl-Module-ScanDeps
apt-cyg install perl-Module-Signature
apt-cyg install perl-Mojolicious
apt-cyg install perl-Mozilla-CA
apt-cyg install perl-MRO-Compat
apt-cyg install perl-namespace-autoclean
apt-cyg install perl-namespace-clean
apt-cyg install perl-Net-HTTP
apt-cyg install perl-Net-IP
apt-cyg install perl-Net-SMTP-SSL
apt-cyg install perl-Net-SSLeay
apt-cyg install perl-Net-XMPP
apt-cyg install perl-Number-Compare
apt-cyg install perl-Package-Stash
apt-cyg install perl-Package-Stash-XS
apt-cyg install perl-PAR
apt-cyg install perl-Params-Util
apt-cyg install perl-Params-Validate
apt-cyg install perl-Params-ValidationCompiler
apt-cyg install perl-PAR-Dist
apt-cyg install perl-PAR-Packer
apt-cyg install perl-Parse-RecDescent
apt-cyg install perl-Path-Class
apt-cyg install perl-Path-Tiny
apt-cyg install perl-POD2-Base
apt-cyg install perl-Pod-Coverage
apt-cyg install perl-Pod-Escapes
apt-cyg install perl-Pod-Simple
apt-cyg install perl-Probe-Perl
apt-cyg install perl-Readonly
apt-cyg install perl-Readonly-XS
apt-cyg install perl-Regexp-Common
apt-cyg install perl-Role-Tiny
apt-cyg install perl-Scalar-List-Utils
apt-cyg install perl-Socket
apt-cyg install perl-Socket6
apt-cyg install perl-Specio
apt-cyg install perl-Spiffy
apt-cyg install perl-Sub-Exporter
apt-cyg install perl-Sub-Exporter-Progressive
apt-cyg install perl-Sub-Identify
apt-cyg install perl-Sub-Install
apt-cyg install perl-Sub-Uplevel
apt-cyg install perl-SUPER
apt-cyg install perl-Tee
apt-cyg install perl-TermReadKey
apt-cyg install perl-Term-ReadLine-Gnu
apt-cyg install perl-Term-ReadLine-Perl
apt-cyg install perl-Term-Table
apt-cyg install perl-Test-Base
apt-cyg install perl-Test-CPAN-Meta
apt-cyg install perl-Test-Deep
apt-cyg install perl-Test-Differences
apt-cyg install perl-Test-EOL
apt-cyg install perl-Test-Exception
apt-cyg install perl-Test-Fatal
apt-cyg install perl-Test-Harness
apt-cyg install perl-Test-Inter
apt-cyg install perl-Test-LeakTrace
apt-cyg install perl-Test-MockModule
apt-cyg install perl-Test-Needs
apt-cyg install perl-Test-NoTabs
apt-cyg install perl-Test-NoWarnings
apt-cyg install perl-Test-Pod
apt-cyg install perl-Test-Pod-Coverage
apt-cyg install perl-Test-Reporter
apt-cyg install perl-Test-Reporter-Transport-Metabase
apt-cyg install perl-Test-Requires
apt-cyg install perl-Test-RequiresInternet
apt-cyg install perl-Test-Script
apt-cyg install perl-Test-Simple
apt-cyg install perl-Test-TrailingSpace
apt-cyg install perl-Test-Warn
apt-cyg install perl-Test-Warnings
apt-cyg install perl-Test-Without-Module
apt-cyg install perl-Test-YAML
apt-cyg install perl-Text-BibTeX
apt-cyg install perl-Text-CharWidth
apt-cyg install perl-Text-CSV
apt-cyg install perl-Text-CSV_XS
apt-cyg install perl-Text-Diff
apt-cyg install perl-Text-Glob
apt-cyg install perl-Text-Roman
apt-cyg install perl-Text-Template
apt-cyg install perl-Text-WrapI18N
apt-cyg install perl-TimeDate
apt-cyg install perl-Tk
apt-cyg install perl-Tk-Canvas-GradientColor
apt-cyg install perl-Tk-ColoredButton
apt-cyg install perl-Tk-EntryCheck
apt-cyg install perl-Tk-Getopt
apt-cyg install perl-Tk-Pod
apt-cyg install perl-Try-Tiny
apt-cyg install perl-Types-Serialiser
apt-cyg install perl-Unicode-Collate
apt-cyg install perl-Unicode-LineBreak
apt-cyg install perl-Unicode-Normalize
apt-cyg install perl-URI
apt-cyg install perl-User-Identity
apt-cyg install perl-Variable-Magic
apt-cyg install perl-Win32
apt-cyg install perl-Win32-API
apt-cyg install perl-Win32-GUI
apt-cyg install perl-WWW-Curl
apt-cyg install perl-WWW-RobotRules
apt-cyg install perl-Wx
apt-cyg install perl-XML-DOM
apt-cyg install perl-XML-LibXML
apt-cyg install perl-XML-LibXML-Simple
apt-cyg install perl-XML-LibXSLT
apt-cyg install perl-XML-NamespaceSupport
apt-cyg install perl-XML-Parser
apt-cyg install perl-XML-RegExp
apt-cyg install perl-XML-SAX
apt-cyg install perl-XML-SAX-Base
apt-cyg install perl-XML-SAX-Expat
apt-cyg install perl-XML-Simple
apt-cyg install perl-XML-Stream
apt-cyg install perl-XML-Writer
apt-cyg install perl-XML-XPath
apt-cyg install perl-XSLoader
apt-cyg install perl-YAML
apt-cyg install perl-YAML-LibYAML
apt-cyg install perl-YAML-Tiny
apt-cyg install bzr
apt-cyg install idle
apt-cyg install idle3
apt-cyg install mercurial
apt-cyg install pylint
apt-cyg install python
apt-cyg install python3
apt-cyg install python3-caca
apt-cyg install python3-cairo
apt-cyg install python3-cairo-devel
apt-cyg install python3-cffi
apt-cyg install python3-chardet
apt-cyg install python3-configobj
apt-cyg install python3-cryptography
apt-cyg install python3-cython
apt-cyg install python3-dbus
apt-cyg install python3-devel
apt-cyg install python3-docutils
apt-cyg install python3-gi
apt-cyg install python3-imaging
apt-cyg install python3-libxml2
apt-cyg install python3-lxml
apt-cyg install python3-numpy
apt-cyg install python3-openssl
apt-cyg install python3-ply
apt-cyg install python3-pyasn1
apt-cyg install python3-pycparser
apt-cyg install python3-pygments
apt-cyg install python3-requests
apt-cyg install python3-setuptools
apt-cyg install python3-simplejson
apt-cyg install python3-six
apt-cyg install python3-speechd
apt-cyg install python3-tkinter
apt-cyg install python3-unidecode
apt-cyg install python3-urllib3
apt-cyg install python3-xdg
apt-cyg install python3-yaml
apt-cyg install python3-zmq
apt-cyg install python-beautifulsoup
apt-cyg install python-cairo
apt-cyg install python-cairo-devel
apt-cyg install python-cffi
apt-cyg install python-chardet
apt-cyg install python-chm
apt-cyg install python-cryptography
apt-cyg install python-cython
apt-cyg install python-devel
apt-cyg install python-docutils
apt-cyg install python-enum34
apt-cyg install python-gi-common
apt-cyg install python-httplib2
apt-cyg install python-imaging
apt-cyg install python-isodate
apt-cyg install python-jinja2
apt-cyg install python-libxml2
apt-cyg install python-libxslt
apt-cyg install python-logilab-astng
apt-cyg install python-logilab-common
apt-cyg install python-lxml
apt-cyg install python-markupsafe
apt-cyg install python-numpy
apt-cyg install python-openssl
apt-cyg install python-pexpect
apt-cyg install python-ply
apt-cyg install python-pyasn1
apt-cyg install python-pycparser
apt-cyg install python-pygments
apt-cyg install python-pyparsing
apt-cyg install python-requests
apt-cyg install python-setuptools
apt-cyg install python-simplejson
apt-cyg install python-six
apt-cyg install python-sphinx
apt-cyg install python-tkinter
apt-cyg install python-twisted
apt-cyg install python-unidecode
apt-cyg install python-urllib3
apt-cyg install python-xdg
apt-cyg install python-yaml
apt-cyg install python-zmq
apt-cyg install python-zope.interface
apt-cyg install bash
apt-cyg install bash-completion
apt-cyg install clisp
apt-cyg install dash
apt-cyg install dbus-bash-completion
apt-cyg install luit
apt-cyg install mintty
apt-cyg install xterm
apt-cyg install a2ps
apt-cyg install ascii
apt-cyg install asciidoc
apt-cyg install biber
apt-cyg install boxes
apt-cyg install build-docbook-catalog
apt-cyg install chm2pdf
apt-cyg install chmlib
apt-cyg install dblatex
apt-cyg install docbook-xsl
apt-cyg install ebook-tools
apt-cyg install figlet
apt-cyg install gettext
apt-cyg install groff
apt-cyg install groff-perl
apt-cyg install groff-X11
apt-cyg install gtypist
apt-cyg install gv
apt-cyg install html2ps
apt-cyg install iso-codes
apt-cyg install iso-codes-devel
apt-cyg install isoquery
apt-cyg install less
apt-cyg install libaspell15
apt-cyg install libepub0
apt-cyg install libosp5
apt-cyg install libthai0
apt-cyg install OpenSP
apt-cyg install par
apt-cyg install patchutils
apt-cyg install po4a
apt-cyg install poppler-data
apt-cyg install sgml-common
apt-cyg install suomi-malaga
apt-cyg install texinfo
apt-cyg install texinfo-tex
apt-cyg install xmlto
apt-cyg install asciinema
apt-cyg install astyle
apt-cyg install checkbashisms
apt-cyg install colordiff
apt-cyg install csih
apt-cyg install cygcheck-dep
apt-cyg install cygutils-extra
apt-cyg install dateutils
apt-cyg install diffutils
apt-cyg install dos2unix
apt-cyg install gnupg
apt-cyg install keychain
apt-cyg install libhdf5_10
apt-cyg install libsasl2_3
apt-cyg install ncurses-demo
apt-cyg install patchutils
apt-cyg install rebase
apt-cyg install tack
apt-cyg install tig
apt-cyg install tmux
apt-cyg install tzcode
apt-cyg install adobe-source-code-pro-fonts
apt-cyg install adobe-source-sans-pro-fonts
apt-cyg install adobe-source-serif-pro-fonts
apt-cyg install appres
apt-cyg install artwiz-aleczapka-fonts
apt-cyg install at-spi2-core
apt-cyg install bitstream-vera-fonts
apt-cyg install caladea-fonts
apt-cyg install cantarell-fonts
apt-cyg install carlito-fonts
apt-cyg install cygutils-x11
apt-cyg install damageproto
apt-cyg install dbus-x11
apt-cyg install dejavu-fonts
apt-cyg install desktop-file-utils
apt-cyg install editres
apt-cyg install faience-icon-theme
apt-cyg install fixesproto
apt-cyg install fontconfig
apt-cyg install font-tektronix-misc
apt-cyg install fonttosfnt
apt-cyg install font-util
apt-cyg install gnome-menus
apt-cyg install gtk2.0-engines-pixmap
apt-cyg install gtk-update-icon-cache
apt-cyg install gv
apt-cyg install harfbuzz
apt-cyg install hicolor-icon-theme
apt-cyg install icon-naming-utils
apt-cyg install libdmx1
apt-cyg install liberation-fonts
apt-cyg install libGLU1
apt-cyg install libglut3
apt-cyg install libxcb-image0
apt-cyg install libxcb-keysyms1
apt-cyg install libxcb-util1
apt-cyg install libXm4
apt-cyg install libXm-devel
apt-cyg install linux-libertine-fonts
apt-cyg install listres
apt-cyg install mkfontdir
apt-cyg install mkfontscale
apt-cyg install oxygen-fonts
apt-cyg install renderproto
apt-cyg install rgb
apt-cyg install scrnsaverproto
apt-cyg install sessreg
apt-cyg install setxkbmap
apt-cyg install shared-mime-info
apt-cyg install showfont
apt-cyg install sj-fonts
apt-cyg install sound-theme-freedesktop
apt-cyg install tcl-tk
apt-cyg install tcl-tk-devel
apt-cyg install terminus-fonts
apt-cyg install tigervnc
apt-cyg install tigervnc-server
apt-cyg install tigervnc-server-module
apt-cyg install unifont
apt-cyg install unifont-fonts
apt-cyg install unifont-viewer
apt-cyg install viewres
apt-cyg install x11vnc
apt-cyg install xauth
apt-cyg install xbitmaps
apt-cyg install xclip
apt-cyg install xclipboard
apt-cyg install xconsole
apt-cyg install xcursorgen
apt-cyg install xcursor-themes
apt-cyg install xdg-user-dirs
apt-cyg install xdg-utils
apt-cyg install xdpyinfo
apt-cyg install xev
apt-cyg install xf86-video-dummy
apt-cyg install xf86-video-nested
apt-cyg install xfd
apt-cyg install xfontsel
apt-cyg install xhost
apt-cyg install xinit
apt-cyg install xinput
apt-cyg install xkbcomp
apt-cyg install xkbevd
apt-cyg install xkbprint
apt-cyg install xkbutils
apt-cyg install xkeyboard-config
apt-cyg install xkill
apt-cyg install xlaunch
apt-cyg install xlsatoms
apt-cyg install xlsclients
apt-cyg install xlsfonts
apt-cyg install xmag
apt-cyg install xmessage
apt-cyg install xmodmap
apt-cyg install xmon
apt-cyg install xorg-scripts
apt-cyg install xorg-server
apt-cyg install xorg-server-common
apt-cyg install xorg-server-extra
apt-cyg install xorg-x11-fonts-dpi100
apt-cyg install xorg-x11-fonts-dpi75
apt-cyg install xorg-x11-fonts-misc
apt-cyg install xorg-x11-fonts-Type1
apt-cyg install xpr
apt-cyg install xprop
apt-cyg install xrdb
apt-cyg install xrefresh
apt-cyg install xscope
apt-cyg install xsel
apt-cyg install xset
apt-cyg install xsetroot
apt-cyg install xsm
apt-cyg install xstdcmap
apt-cyg install xterm
apt-cyg install xwd
apt-cyg install xwinclip
apt-cyg install xwininfo
apt-cyg install xwin-xdg-menu
apt-cyg install xwud
