#!/usr/bin/env perl

use 5.008000;
use strict;
use warnings 'all';

use Carp;
use Cwd;
use File::Basename;
use File::Temp;
use Getopt::Long qw(GetOptionsFromArray :config no_ignore_case);
use Pod::Usage;
use POSIX qw(uname);


# Parse options
my ($opt_help, $opt_t, $opt_o);
GetOptionsFromArray(
    \@ARGV,
    'help|h'       => \$opt_help,
    't|duration=s' => \$opt_t,
    'o|output=s'   => \$opt_o,
) or croak('Error parsing command line arguments');

# Handle help option
pod2usage(-exitval => 0) if ($opt_help);

if(!defined($opt_o) || $opt_o eq '') {
    print STDERR "Option '-o' or '--output' is mandatory\n";
    pod2usage(-exitval => 1);
}

# Default option values
$opt_t //= 30;

# Get the recorded window parameters
my $xwin_info = `xwininfo`;
croak('Error getting X-Window information') if($?);

my ($title, $x, $y, $width, $height);
$xwin_info =~ m/Window id:\s+\w+\s+"([^"]+)"/g;
$title = $1;
$xwin_info =~ m/Absolute upper-left X:\s*(\d+)/g;
$x = $1;
$xwin_info =~ m/Absolute upper-left Y:\s*(\d+)/g;
$y = $1;
$xwin_info =~ m/Width:\s*(\d+)/g;
$width = $1;
$xwin_info =~ m/Height:\s*(\d+)/g;
$height = $1;

my $tmp = File::Temp->new(SUFFIX => '.mkv');
close($tmp);
my $mkv = "$tmp";

my ($sysname) = uname;
if($sysname =~ m/CYGWIN/) {
    my @args = ("ffmpeg");
    push(@args, '-video_size', $width.'x'.$height);
    push(@args, '-framerate', '25');
    push(@args, '-f', 'gdigrab');
    push(@args, '-i', 'title='.$title);
    push(@args, '-c:v', 'libx264', '-crf', '0', '-preset', 'ultrafast');
    push(@args, $mkv);
    my $cmd_cli = "'".join("' '", @args)."'";
    print "system $cmd_cli\n";
    system @args == 0
        or die("Unable to execute command: $cmd_cli");
} else {
    my @args = ("ffmpeg");
    push(@args, '-video_size', $width.'x'.$height);
    push(@args, '-framerate', '25');
    push(@args, '-f', 'x11grab');
    push(@args, '-i', ':0.0+'.$x.','.$y);
    push(@args, '-c:v', 'libx264', '-crf', '0', '-preset', 'ultrafast');
    push(@args, $mkv);
    my $cmd_cli = "'".join("' '", @args)."'";
    print "system $cmd_cli\n";
    system @args == 0
        or die("Unable to execute command: $cmd_cli");
}

my @args = ();
push(@args, 'ffmpeg');
push(@args, '-i', $mkv);
push(@args, '-c:v', 'libvpx-vp9', '-crf', '0', '-preset', 'veryslow');
push(@args, $opt_o);
my $cmd_cli = "'".join("' '", @args)."'";
print "system $cmd_cli\n";
system @args == 0
    or die("Unable to execute command: $cmd_cli");

__END__
=head1 NAME

ffmpeg-helper - Helper script to record an X-Window with ffmpeg-record

=head1 SYNOPSIS

B<ffmpeg-helper> B<-h>|B<--help>

B<ffmpeg-helper> [B<OPTIONS>] B<-o> I<FILE>

=head1 DESCRIPTION

This tool helps record a specific B<X11> window using B<ffmpeg>. When
run, the script will ask the user to pick the desired X-Window using the mouse.
The recording will then start for the specified duration.

Internally the script uses B<xwininfo> to obtain the position and size of the
recorded video. These parameters are not updated while the video is recorded.
It the recorded window is moved it will leave the area of recording and be
only partially visible in the resulting video.

=head1 OPTIONS

=over

=item B<-h>|B<--help>

Print the usage, help and version information for this program and exit.

=item B<-o> I<FILE>|B<--output>=I<FILE>

Sets the output file for the recorded video.

=item B<-t> I<DURATION>|B<--duration>=I<DURATION>

Sets the recording duration in seconds. Default is 30 seconds.

=back

=head1 SEE ALSO

ffmpeg(1), xwininfo(1)

=head1 AUTHOR

Frederic JARDON <frederic.jardon@gmail.com>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2018 by Frederic JARDON <frederic.jardon@gmail.com>

This program is free software; you can redistribute it and/or modify
it under the MIT license.

=cut
