#!/usr/bin/env bash

# Exit on any errors
set -e

# A function to output on stderr
function echoerr() { echo "$@" 1>&2; }

# Configuration
CRONDIR=~/.local/etc/cron

# Get this script name
script="$0"

# Sanity check
scriptdir="$1"
if [ -z "${scriptdir}" ]; then
    echoerr "Usage: ${script} <directory>"
    echoerr ""
    echoerr "Run all scripts inside a directory."
    exit 1
fi

SCRIPTDIR="${CRONDIR}/${scriptdir}"
if [ ! -d "${SCRIPTDIR}" ]; then
    echoerr "Directory: '${SCRIPTDIR}' doesn't exist. ABORTING!"
    exit 1
fi


# Load custom cron environment if present
if [ -e "${CRONDIR}/environ.bash" ]; then
    source "${CRONDIR}/environ.bash"
fi

# Run the commands
for script in "${SCRIPTDIR}"/*
do
    if [ -f "${script}" -a -x "${script}" ]; then
        echo "Running script: '${script}' ..."
        echo "---------------"
        ( "${script}" )
        echo -e "\f"
    fi
done


