#!/usr/bin/env bash

# =============================================================================
# Exit on any errors
set -e
function echoerr() { echo "$@" 1>&2; }
# =============================================================================

# =============================================================================
# Configure some shell variables
PATH=${PATH}:${HOME}/.local/bin
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/.local/lib
DATAROOTDIR="${HOME}/.local/share"
# =============================================================================

# =============================================================================
# Autodetect current install capabilities
function has_prog() {
    hash "$1" > /dev/null 2>&1
    return $?
}

REQUIRED_PROGS=(curl git grep install mktemp sed)
has_errors=
for p in ${REQUIRED_PROGS[@]};
do
    if ! has_prog "${p}"; then
       echoerr " - ${p} required"
       has_errors=Yes
    fi
done
[[ -z "${has_errors}" ]] || exit 1

os_name=
if has_prog uname; then
    os_name=$(uname -s)
fi
# =============================================================================

# =============================================================================
# Prepare temporary directory to unarchive files
# ----------------------------------------------
RUN_CWD=$(pwd)
SHAR_TMPDIR=$(mktemp -d)
cd "${SHAR_TMPDIR}"
echo "Unsharing files in ${SHAR_TMPDIR} ..."
cat <<'SETUP_SHAR_EOF'> setup.shar
# @SHAR_ARCHIVE@
SETUP_SHAR_EOF
/bin/sh setup.shar
# =============================================================================


# Prepare backups directory
DATE=$(date '+%Y%m%d')
HOUR=$(date '+%H%M%S')
BACKUPDIR=~/.backups/${DATE}/${HOUR}
install -m 0700 -d ${BACKUPDIR}

# Backup files
echo "shell ..."
if [ -e ~/.profile ]; then
    cp -f ~/.profile "${BACKUPDIR}"
fi
if [ -e ~/.bash_profile ]; then
    cp -f ~/.bash_profile "${BACKUPDIR}"
fi
if [ -e ~/.bashrc ]; then
    cp -f ~/.bashrc "${BACKUPDIR}"
fi
if [ ! -e ~/.path_dirs ]; then
    cat <<DOT_PROFILE_PATHS_EOF > ~/.path_dirs
# Directory path in this file are scanned by .bash_profile
# to setup the following variables:
#  - PATH
#  - LD_LIBRARY_PATH
#  - MANPATH
#  - INFOPATH
#  - PERL5LIB
#  - PKG_CONFIG_PATH

${HOME}/.local
${HOME}/.local/share/perl5
DOT_PROFILE_PATHS_EOF
fi
install -m 0644 dot_profile      ~/.profile
install -m 0644 dot_bash_profile ~/.bash_profile
install -m 0644 dot_bashrc       ~/.bashrc

# XWindow
echo "XWindow ..."
if [ -e ~/.Xresources ]; then
    cp -f ~/.Xresources ${BACKUPDIR}
fi
install -m 0644 dot_Xresources ~/.Xresources

# .local setup
echo "local ..."
install -m 0755 -d ~/.local/bin
install -m 0755 -d ~/.local/lib
install -m 0755 -d ~/.local/share
install -m 0755 -d ~/.local/var/lock
install -m 0755 -d ~/.local/var/log
install -m 0755 -d ~/.local/var/run
install -m 0755 -d ~/.local/etc/cron
install -m 0755 -d ~/.local/etc/profile.d
install -m 0755 runcron ~/.local/bin
export PATH=${PATH}:~/.local/bin

# Cygwin
if [[ "${os_name}" == CYGWIN* ]]; then
    echo "Cygwin ..."
    if [ -e ~/.XWinrc ]; then
        cp -f ~/.XWinrc ${BACKUPDIR}
    fi
    install -m 0644 dot_XWinrc ~/.XWinrc

    if ! has_prog apt-cyg; then
        git clone https://github.com/transcode-open/apt-cyg.git apt-cyg
        install -m 0755 apt-cyg/apt-cyg ~/.local/bin
    fi
fi

# Cron setup
echo "cron ..."
if has_prog crontab; then
    install -m 0755 -d ~/.local/etc/cron
    install -m 0755 -d ~/.local/etc/cron/hourly
    install -m 0755 -d ~/.local/etc/cron/daily
    install -m 0755 -d ~/.local/etc/cron/daily-4
    install -m 0755 -d ~/.local/etc/cron/daily-8
    install -m 0755 -d ~/.local/etc/cron/daily-12
    install -m 0755 -d ~/.local/etc/cron/daily-16
    install -m 0755 -d ~/.local/etc/cron/daily-20
    install -m 0755 -d ~/.local/etc/cron/weekly
    install -m 0755 -d ~/.local/etc/cron/monthly
    install -m 0755 -d ~/.local/etc/cron/yearly
    install -m 0755 -d ~/.local/etc/cron/commands
    touch ~/.local/etc/cron/environ.bash

    crontab -l > "${BACKUPDIR}/crontab"
    tmpcrontab=$(mktemp)
    grep -v ~/.local/bin/runcron "${BACKUPDIR}/crontab" \
         > "${tmpcrontab}"
    echo "0  * * * *" ~/.local/bin/runcron hourly   >> "${tmpcrontab}"
    echo "0  0 * * *" ~/.local/bin/runcron daily    >> "${tmpcrontab}"
    echo "0  4 * * *" ~/.local/bin/runcron daily-4  >> "${tmpcrontab}"
    echo "0  8 * * *" ~/.local/bin/runcron daily-8  >> "${tmpcrontab}"
    echo "0 12 * * *" ~/.local/bin/runcron daily-12 >> "${tmpcrontab}"
    echo "0 16 * * *" ~/.local/bin/runcron daily-16 >> "${tmpcrontab}"
    echo "0 20 * * *" ~/.local/bin/runcron daily-20 >> "${tmpcrontab}"
    echo "0  0 * * 0" ~/.local/bin/runcron weekly   >> "${tmpcrontab}"
    echo "0  0 1 * *" ~/.local/bin/runcron monthly  >> "${tmpcrontab}"
    echo "0  0 1 1 *" ~/.local/bin/runcron yearly   >> "${tmpcrontab}"
    crontab "${tmpcrontab}"
    rm -f "${tmpcrontab}"
fi

# Fonts
echo "fonts ..."
install -d ~/.fonts
install -d ~/.local/share/fonts
if has_prog fc-cache; then
    if [ ! -e ~/.local/share/fonts/power-line ]; then
        git clone https://github.com/powerline/fonts.git \
              ~/.local/share/fonts/power-line
        fc-cache -f ~/.local/share/fonts
    fi
fi

# vim
echo "vim ..."
touch ~/.vimrc
cp -f ~/.vimrc ${BACKUPDIR}
if [ ! -e ~/.vim/bundle/Vundle.vim ]; then
    git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi
install -m 0644 dot_vimrc ~/.vimrc

# Python
echo "Python ..."
if ! has_prog pip3; then
    easy_install_prog=$(compgen -c 'easy_install-3' | head -n 1)
    if has_prog "${easy_install_prog}"; then
        if ! has_prog pip3; then
            ${easy_install_prog} --user pip
        fi
    fi
fi
if ! has_prog pip2; then
    easy_install_prog=$(compgen -c 'easy_install-2' | head -n 1)
    if has_prog "${easy_install_prog}"; then
        if ! has_prog pip2; then
            ${easy_install_prog} --user pip
        fi
    fi
fi
if ! has_prog cppman; then
    if has_prog pip3; then
        pip3 install --user cppman
    fi
fi
if ! has_prog ribosome.py; then
    git clone https://github.com/sustrik/ribosome.git ribosome
    install -m 0755 ribosome/ribosome.py ~/.local/bin/
fi

# Perl
echo "Perl ..."
if [ ! -e ~/.local/share/perl5 ]; then
    curl -O http://search.cpan.org/CPAN/authors/id/H/HA/HAARG/local-lib-2.000018.tar.gz
    tar zxvf local-lib-2.000018.tar.gz
    cd local-lib-2.000018
    perl Makefile.PL --bootstrap=${HOME}/.local/share/perl5
    make test && make install
    cd ..
    perl -I${HOME}/.local/share/perl5/lib/perl5 -Mlocal::lib=${HOME}/.local/share/perl5 \
        > ~/.local/etc/profile.d/perl5.bash
    . ~/.local/etc/profile.d/perl5.bash
fi

# Gnulib
echo "Gnulib ..."
if ! has_prog gnulib-tool; then
    if [ ! -e ~/.local/share/gnulib ]; then
        git clone git://git.savannah.gnu.org/gnulib.git ~/.local/share/gnulib
    fi
    ln -s ~/.local/share/gnulib/gnulib-tool ~/.local/bin/gnulib-tool
fi


#TeX
echo "TeX ..."
if has_prog kpsewhich; then
    texmf_home=$(kpsewhich -var-value TEXMFHOME)
    mkdir -p "${texmf_home}/tex/latex/"
    git clone https://github.com/aginiewicz/createspace.git "${texmf_home}/tex/latex/createspace"
fi


## emacs
#echo "emacs ..."
#touch ~/.emacs
#cp -f ~/.emacs ${BACKUPDIR}
#install -m 0644 dot_emacs ~/.emacs
#
#if has_prog emacs && has_prog git && has_prog make; then
#    echo "emacs cedet ..."
#    CEDETDIR=cedet-git
#    if [ ! -e "${DATAROOTDIR}/${CEDETDIR}" ]; then
#	    git -C "${DATAROOTDIR}" clone \
#	        'http://git.code.sf.net/p/cedet/git' ${CEDETDIR}
#	    make -C "${DATAROOTDIR}/${CEDETDIR}" EMACS=emacs
#    fi
#fi
#
#if has_prog emacs && has_prog git; then
#    echo "emacs ecb ..."
#    ECBDIR=ecb-git
#    if [ ! -e "${DATAROOTDIR}/${ECBDIR}" ]; then
#	      git -C "${DATAROOTDIR}" clone \
#	          'https://github.com/alexott/ecb.git' ${ECBDIR}
#    fi
#fi


# # gnu global / idutils
# build_idutils=
# if ! has_prog mkid && has_prog curl && has_prog gcc && has_prog make && has_prog tar; then
#     build_idutils=Yes
# fi
# echo "dev tools ..."
# if [[ -n "$build_idutils" ]]; then
#     echo "Building idutils ..."
#     TMPDIR=$(mktemp -d)
#     RELEASE="idutils-4.5"
#     TGZ="${TMPDIR}/${RELEASE}.tar.gz"
#     SRCDIR="${TMPDIR}/${RELEASE}"
#     BUILDDIR="${TMPDIR}/build"
#     curl -s -o "${TGZ}" \
# 	       "http://ftp.gnu.org/gnu/idutils/${RELEASE}.tar.gz"
#     tar -C "${TMPDIR}" -zxf "${TGZ}"
#     mkdir "${BUILDDIR}"
#     cd "${BUILDDIR}"
#     "${SRCDIR}/configure" "--prefix=${HOME}/.local"
#     make
#     make install
#     cd "${SHAR_TMPDIR}"
# fi
#
#
# build_global=
# if ! has_prog global && has_prog curl && has_prog gcc && has_prog make && has_prog tar; then
#     build_global=Yes
# fi
# if [[ -n "$build_global" ]]; then
#     echo "Building GNU global ..."
#     TMPDIR=$(mktemp -d)
#     RELEASE="global-6.5.4"
#     TGZ="${TMPDIR}/${RELEASE}.tar.gz"
#     SRCDIR="${TMPDIR}/${RELEASE}"
#     BUILDDIR="${TMPDIR}/build"
#     curl -s -o "${TGZ}" \
# 	       "http://ftp.gnu.org/gnu/global/${RELEASE}.tar.gz"
#     tar -C "${TMPDIR}" -zxf "${TGZ}"
#     mkdir "${BUILDDIR}"
#     cd "${BUILDDIR}"
#     "${SRCDIR}/configure" "--prefix=${HOME}/.local"
#     make
#     make install
#     cd "${SHAR_TMPDIR}"
# fi
#
