# .bash_profile executed by bash(1) for login shells.

. ~/.profile

if [ -d ~/.local/etc/profile.d ]; then
    for profile_script in ~/.local/etc/profile.d/*.bash
    do
        [ -e "${profile_script}" ] || continue
        . "${profile_script}"
    done
fi

# Bash reads:
# - .bash_profile for interactive login shells
# - .bashrc for non-login intecactive shells.
#
# source the user's bashrc if it exists
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
