" In case usual windows move command doesn't work
" :nmap <silent> <A-Up> :wincmd k<CR>
" :nmap <silent> <A-Down> :wincmd j<CR>
" :nmap <silent> <A-Left> :wincmd h<CR>
" :nmap <silent> <A-Right> :wincmd l<CR>

" Highligth characters after 80th columns
set colorcolumn=80
highlight ColorColumn ctermbg=lightgrey guibg=lightgrey

" Use explorer in tree mode
let g:netrw_liststyle=3

" Use soft tabs, size 4
set tabstop=4 shiftwidth=4 expandtab

" Auto indent file
autocmd FileType *      set formatoptions=tcql nocindent comments&
autocmd FileType c,cpp  set formatoptions=croql cindent comments=sr:/*,mb:*,ex:*/,://
set autoindent

" Highlight searched targets
set hlsearch

" Show line numbers
set number

" Encoding utf8
set encoding=utf8

" Block cursor
let &t_SI.="\e[1 q"
let &t_EI.="\e[1 q"
let &t_ti.="\e[1 q"
let &t_te.="\e[1 q"

" Show cursor line
hi CursorLine cterm=NONE ctermbg=darkred ctermfg=white
hi CursorColumn cterm=NONE ctermbg=darkred ctermfg=white
set cursorline
nnoremap <Leader>c :set cursorcolumn!

set nocompatible              " be iMproved, required

syntax on
set ruler

set nu
set nobackup
set smarttab
set tabstop=4
set shiftwidth=4
set expandtab

" copy the current text selection to the system clipboard
if has('gui_running') || has('nvim') && exists('$DISPLAY')
  noremap <Leader>y "+y
else
  " copy to attached terminal using the yank(1) script:
  noremap <silent> <Leader>y y:call system('yank', @0)<Return>
endif

hi Terminal ctermbg=black ctermfg=white
